- obs-vkcapture/PKGBUILD
I did a test of this PKGBUILD:
1. Build is fine
2. OBS is fine, I captured the game through `obs-gamecapture`
> obs-vkcapture

- cachyos-obs-studio/6207.patch
- cachyos-obs-studio/PKGBUILD
Added patch for a pipewire audio capture.
> pipewire patch

- cachyos-gaming-meta/PKGBUILD
I adjusted packages to be more relevant
> Refactoring

- intel-packages/intel-makedepends-stage-1/intel-makedepends/vc-intrinsics/PKGBUILD
Fix LLVM-15 and LLVM-ToT builds
https://github.com/intel/vc-intrinsics/releases/tag/v0.9.0
> Update v 0.9.0

- cachy-browser/PKGBUILD
[PR on CachyOS-Browser-Common -> Add devtools-bypass patch](https://github.com/CachyOS/CachyOS-Browser-Common/pull/2) PR should be merged before merging this.
> Add Devtools bypass patches to PKGBUILD

- obs-packages/obs-vkcapture/PKGBUILD
Fixed validation errors in Vulkan layer
>  obs-vkcapture 1.2.2

- intel-packages/intel-makedepends-stage-1/intel-graphics-compiler/PKGBUILD
Release: https://github.com/intel/intel-graphics-compiler/releases
> intel-graphics-compiler-1.0.12504.5

- obs-packages/obs-vaapi/PKGBUILD
https://github.com/fzwoch/obs-vaapi/releases/tag/0.2.0
> obs-vaapi update

- hyprland-git/PKGBUILD
Hello, in the new merge of wlroots dep by Hyprland-dev we need to put new deps 
Best Regards,
NextWorks
> Introduce New Depends for hyprland-git

- obs-packages/obs-vkcapture/PKGBUILD
https://github.com/nowrep/obs-vkcapture/releases/tag/v1.3.1
> obs-vkcapture update 1.3.1

- cachyos-qtile-settings/PKGBUILD
i forgot to add two essential dependencies for theming purposes
> New dependencies, bump version

- cachyos-qtile-settings/PKGBUILD
New icons were added, and all icons are now separate files
> Add new icons, bump version

- cachyos-qtile-settings/PKGBUILD
i forgot to add a folder and because of that icons were not appearing after installation
> Bump version

- obs-packages/obs-vkcapture/PKGBUILD
> Update PKGBUILD obs-vkcapture-1.3.2

- pacman/PKGBUILD
- pacman/static_sqlite.patch
Static linking pacman with a v3 compiled sqlite3 inside default CachyOS docker.
> feat(pacman static): static linking pacman

- clipman/PKGBUILD
Update version, change repository.
> clipman version

- chwd/PKGBUILD
Depends on: https://github.com/CachyOS/chwd/pull/66
P. S. I'm not sure if we should bump new pkgver or just increase pkgrel for this.
> Merge chwd and chwd-db into one package

- cachyos-settings/.SRCINFO
- cachyos-settings/PKGBUILD
- cachyos-settings/cachyos-settings.install
And remove the enabling of optimize-interruptfreq and pci-latency services.
> cachyos-settings: Bump new pkgver

- toolchain/gcc/PKGBUILD
new stable commit tested in-house
> version(gcc): update commit

- svt-av1-psy/.SRCINFO
- svt-av1-psy/PKGBUILD
Continuation of this PR: https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/141
This time though, it's actually a separate PKGBUILD so that users not only have to manually install it, but it'll get updated separately I believe.
Any improvements welcome.
> Adding svt-av1-psy as a separate package

- svt-av1-psy/.SRCINFO
- svt-av1-psy/PKGBUILD
Title is self explanatory.
If I've made any beginner mistakes regarding versioning, please let me know so I can put it in my documentation.
> Updating svt-av1 and svt-av1-psy to 2.0.0 release

- proton-cachyos/proton-cachyos/PKGBUILD
- proton-cachyos/proton-cachyos/disable-fastsync.patch
- proton-cachyos/proton-cachyos/fastsync.patch
Note: I don't use CachyOS but I ported this on my gentoo machine so I figured I might as well submit it
Needs testing and probably a bit of cleanup
> proton-cachyos: Proton 9.0 port of fastsync.patch

- deckify/jupiter-hw-support/PKGBUILD
- deckify/jupiter-hw-support/pythonhid.patch
> Finally fix damn controller

- proton-cachyos/proton-cachyos/.SRCINFO
- proton-cachyos/proton-cachyos/PKGBUILD
https://github.com/loathingKernel/PKGBUILDs/actions/runs/9220762919
> proton-cachyos: Bump pkgrel

- handheld/cachyos-handheld/PKGBUILD
- handheld/cachyos-handheld/cachyos-handheld.install
- handheld/jupiter-hw-support/.SRCINFO
- handheld/jupiter-hw-support/PKGBUILD
- handheld/jupiter-hw-support/cachyos-automount.patch
- handheld/jupiter-hw-support/steamos-btrfs-automount.patch
- handheld/jupiter-hw-support/udev-automount-rules.patch
> Add patches for steamos-automount and bump jupiter-hw-support version

- handheld/jupiter-hw-support/.SRCINFO
- handheld/jupiter-hw-support/PKGBUILD
- handheld/jupiter-hw-support/priv-write.patch
Requires [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/fac956aa6d449dbde34c06b1ca1ae123dc237c25) to have been pushed to repos first
> jupiter-hw-support: add priv-write patch

- systemd-boot-manager/.SRCINFO
- systemd-boot-manager/PKGBUILD
- systemd-boot-manager/sdboot-manage
Requires [https://github.com/CachyOS/CachyOS-Handheld/commit/e9e9d1882633317bd608e7164aef9fe219179788](https://github.com/CachyOS/CachyOS-Handheld/commit/e9e9d1882633317bd608e7164aef9fe219179788) to be pushed at the same time
> systemd-boot-manager: switch sourcing method

- power-profiles-daemon/.SRCINFO
- power-profiles-daemon/.nvchecker.toml
- power-profiles-daemon/PKGBUILD
> power-profiles-daemon: Cherrypick !208

- cachyos-benchmarker/.SRCINFO
- cachyos-benchmarker/PKGBUILD
python-matplotlib needed for graph
> [Benchmarker] Add missing dependency

- proton-cachyos/PKGBUILD
- proton-cachyos/nvapi-optical-flow.patch
This PR updates `proton-cachyos` with the latest changes from the nvapi optical flow PR.
> proton-cachyos: update nvapi-optical-flow.patch

- lenovolegionlinux-dkms/.SRCINFO
- lenovolegionlinux-dkms/PKGBUILD
- lenovolegionlinux-dkms/lenovolegionlinux.install
- lenovolegionlinux/.SRCINFO
- lenovolegionlinux/PKGBUILD
- lenovolegionlinux/lenovolegionlinux.install
This PR add the stable PKGBUILDS for LenovoLegionLinux
> LenovoLegionLinux Stable PKGBUILDS

- proton-cachyos/PKGBUILD
- proton-cachyos/nvapi-optical-flow.patch
- proton-cachyos/proton-optical-flow.patch
More updates from the nvapi optical flow PR.
> proton-cachyos: update nvapi optical flow patches

- cachyos-ksm-settings/.SRCINFO
- cachyos-ksm-settings/10-enable-ksm-by-default.conf
- cachyos-ksm-settings/10-systemd-ksm.conf
- cachyos-ksm-settings/PKGBUILD
- cachyos-ksm-settings/ksmctl
- cachyos-ksm-settings/ksmstats
Separated from cachyos-settings because it is an optional feature.
> cachyos-ksm-settings: New package

- .SRCINFO
- PKGBUILD
Test File
---------
https://raw.githubusercontent.com/joebonrichie/benchmarks/refs/heads/master/pango-layout-profile.c
Benchmark
---------
hyperfine "./pango-layout-profile"
Before: 12.823 s | Now: 11.569 s
> pango: Build with PGO for 1.10x speedup

- lenovolegionlinux-dkms/PKGBUILD
Hi
I am not that much familiar with `PKGBUILD` but it created the folder `-1.0.0` in `/usr/src`
> Fix lenovolegionlinux-dkms PKGBUILD

- proton-cachyos/.SRCINFO
- proton-cachyos/PKGBUILD
- wine-cachyos-opt/.SRCINFO
- wine-cachyos-opt/PKGBUILD
- wine-cachyos/.SRCINFO
- wine-cachyos/PKGBUILD
- **proton-cachyos: version 9.0-20250106**
- **wine-cachyos: version 9.0-20250106**
- **wine-cachyos-opt: version 9.0-20250106**
> Wine/Proton 9.0-20250106

- cachyos-mirrorlist/PKGBUILD
- cachyos-mirrorlist/cachyos-mirrorlist
> cachyos-mirrorlist: Fix NJU mirror link

- cachy-browser/.SRCINFO
- cachy-browser/PKGBUILD
> 🔖 cachy-browser: Bump version

- lenovolegionlinux-dkms/PKGBUILD
Fix `pkgname` lenovolegionlinux-dkms
> Fix pkgname lenovolegionlinux-dkms

- wine-cachyos-opt/.SRCINFO
- wine-cachyos-opt/PKGBUILD
- wine-cachyos-opt/wine-cachyos-remove-icu.patch
- wine-cachyos/.SRCINFO
- wine-cachyos/PKGBUILD
- wine-cachyos/wine-cachyos-remove-icu.patch
- **wine-cachyos: version 9.0-20250126**
- **wine-cachyos-opt: version 9.0-20250126**
> Update wine-cachyos to 9.0-20250126

- cachyos-gaming-meta/.SRCINFO
- cachyos-gaming-meta/PKGBUILD
- wine-cachyos-opt/.SRCINFO
- wine-cachyos-opt/PKGBUILD
- wine-cachyos/.SRCINFO
- wine-cachyos/PKGBUILD
- wine-cachyos: bundle wine-gecko and wine-mono
- wine-cachyos-opt: bundle wine-gecko and wine-mono
- cachyos-gaming-meta: remove wine-gecko and wine-mono, bundled with wine-cachyos
- cachyos-gaming-meta: replace wine-cachyos with wine-cachyos-opt
> Bundle wine-mono and wine-gecko with wine-cachyos/wine-cachyos-opt

- davinci-resolve/.SRCINFO
- davinci-resolve/PKGBUILD
Updating the PKGBUILD to Resolve version 19.1.4.
> update to resolve 19.1.4

- mesa/mesa-git/PKGBUILD
Fix https://github.com/CachyOS/CachyOS-PKGBUILDS/issues/547
> Update lib32-mesa dependecy

- wine-staging/.SRCINFO
- wine-staging/PKGBUILD
- wine-staging/wine-ntsync.patch
- wine/.SRCINFO
- wine/PKGBUILD
- wine/wine-ntsync.patch
- **wine: version 10.5**
- **wine-staging: version 10.5**
> Update wine/wine-staging to 10.5

- cachyos-hooks/.SRCINFO
- cachyos-hooks/PKGBUILD
Fixes issue when pacman update was considered failed due to lack of a notification daemon.
> cachyos-hooks: Bump new pkgver

- wine-staging/.SRCINFO
- wine-staging/PKGBUILD
- wine/.SRCINFO
- wine/PKGBUILD
No changes needed in the patches
> wine/wine-staging: 10.6-2

- proton-cachyos/.SRCINFO
- proton-cachyos/PKGBUILD
- wine-cachyos-opt/.SRCINFO
- wine-cachyos-opt/PKGBUILD
- wine-cachyos/.SRCINFO
- wine-cachyos/PKGBUILD
- **proton-cachyos: version 9.0-20250426**
- **wine-cachyos: version 9.0-20250426**
- **wine-cachyos-opt: version 9.0-20250426**
> proton/wine 9.0-202504026

- cachyos-ksm-settings/.SRCINFO
- cachyos-ksm-settings/PKGBUILD
Closes: https://github.com/CachyOS/CachyOS-PKGBUILDS/issues/602
> cachyos-ksm-settings: Add license

- cachyos-ksm-settings/.SRCINFO
- cachyos-ksm-settings/PKGBUILD
- cachyos-ksm-settings/ksmctl
Closes: https://github.com/CachyOS/CachyOS-PKGBUILDS/issues/604
> cachyos-ksm-settings: Add option to check status

- cachyos-hooks/.SRCINFO
- cachyos-hooks/PKGBUILD
Fixes handling of conflicts with limine-mkinitcpio-hook.
> cachyos-hooks: 2025.05.07

- cachy-browser/.SRCINFO
- cachy-browser/PKGBUILD
Kdialog was added to show notice but not the package to show it
> [cachy-browser] Add req to show notice..

- cachyos-firefox-settings/.SRCINFO
- cachyos-firefox-settings/PKGBUILD
- cachyos-firefox-settings/cachyos.js
> [firefox-settings] Remove ad

- toolchain/binutils/PKGBUILD
- toolchain/gcc/PKGBUILD
- toolchain/glibc/.SRCINFO
- toolchain/glibc/PKGBUILD
- toolchain/libtool/PKGBUILD
- toolchain/linux-api-headers/PKGBUILD
Preapartion for upcoming glibc-rebuild. Merge as soon arch pushes to stable
> glibc: 2.42 + glibc rebuild

- cachy-update/.SRCINFO
- cachy-update/PKGBUILD
https://github.com/Antiz96/arch-update/releases/tag/v3.15.4
> Bump Cachy-Update to v3.15.4

- stacer/.SRCINFO
- stacer/PKGBUILD
Prepared pkgbuild for stacer, tested it, it works for me.
> stacer: add package

- stacer/.SRCINFO
- stacer/.nvchecker.toml
- stacer/PKGBUILD
Please check nvchecker to see if I have done it correctly?
> stacer: 1.5.0
