CachyOS/CachyOS-PKGBUILDS

- cachyos-obs-studio/PKGBUILD
- cachyos-obs-studio/fix_python_binary_loading.patch
- cachyos-obs-studio/ignore_unused_submodules.patch
- obs-gstreamer/PKGBUILD
- obs-vaapi/PKGBUILD
OBS in the Arch Linux repo mission features and dependencies don't lead you in the right way - you must study Arch wiki, and what's next should be installed to OBS. So I decided to fix that.
> Improvements for OBS

- intel-packages/intel-makedepends-stage-1/intel-makedepends/vc-intrinsics/PKGBUILD
Release: https://github.com/intel/vc-intrinsics/releases/tag/v0.11.0   
- Support latest LLVM top-of-trunk updates 
- Support new pass manager 
- Clean-up target platform names list
> vc-intrinsics-0.11.0

- nvlax-git/.SRCINFO
- nvlax-git/PKGBUILD
- nvlax-git/nvlax-install.hook
- nvlax-git/nvlax-upgrade.hook
Although upstream seems to be dead, nvlax still works fine for new driver versions and we don't have to wait for an nvidia-patch.
I'm really not sure if we really need hooks for auto-apply.
@ptr1337
> New package: nvlax-git

- systemd-boot-manager/sdboot-manage
Synchronized discard is terrible
> systemd-boot-manager: Prefer asynchronous discard for Btrfs instead of normal discard

- cachyos-settings/PKGBUILD
If there is a space in the build path name then build will be failed. Minor change, so I don't think we need to bump a new pkgrel.
> cachyos-settings: Fix a missed escaping

- armcord-git/PKGBUILD
- armcord-git/armcord-launcher.sh
- armcord-git/armcord.desktop
- armcord-git/notes.install
Hello, I would like to add a modified PKGBUILD of armcord-git to our repository. Here's what I'm doing:
-  We already have `electron26-bin` in the repository, which we intend to leverage to address screen-sharing issues on Wayland.
-  The modified PKGBUILD will use `electron26-bin` by default, while still retaining the option for users to choose a different electron version if desired. (on `/usr/bin/armcord`)
> Add Armcord-git.

- sqlite3/.SRCINFO
- sqlite3/PKGBUILD
- sqlite3/license.txt
- sqlite3/sqlite-lemon-system-template.patch
Starting a discussion on how could we provide sqlite3-pgo PKGBUILD.
A good benchmark for databases that can be used for PGOing is:
[ClickBench](https://github.com/ClickHouse/ClickBench)
see: https://github.com/zamazan4ik/awesome-pgo/blob/main/sqlite.md
The database for sqlite3 is 15GB, the default test randomly sample 2.2GB.
We could provide those 2.2GB, which compressed are as follows:
```
.rw-r--r--  291M seman 23 Dec 23:39   mydb.tar.xz
.rw-r--r--  334M seman 23 Dec 20:55   mydb.zst
```
But, what about the license of the database? Can we host it?
Any ideas?
@ptr1337 @vnepogodin
> test(sqlite3): adding sqlite-pgo draft for discussion

- openjdk/java-openjdk/.SRCINFO
- openjdk/java-openjdk/PKGBUILD
- openjdk/java-openjdk/clang-lto.patch
- openjdk/java17-openjdk/.SRCINFO
- openjdk/java17-openjdk/PKGBUILD
Builds fine on my rig. Note that JDK 21 requires a special patch to bypass LTO restrictions. This is not required for JDK 17.
> openjdk: Build OpenJDK with Clang

- dracut/PKGBUILD
- dracut/dracut-cachyos.conf
- dracut/dracut-install
- dracut/dracut-remove
Adds `BUILD_UKI` config option, this enables building UKIs and placing them at: `/boot/EFI/Linux/`
Fix incorrect file name used in `dracut-install` script
Ensure `dracut-remove` also deletes the generated UKIs when a kernel is uninstalled
Include `binutils` in the depends array, required for UKI generation
Include `etc/dracut-cachyos.conf` in the backup array, to ensure that the file is not overwritten every time the package is updated
> feat(dracut): `BUILD_UKI` config option

- julia/PKGBUILD
> update(julia): updating, still need to test

- svt-av1-psy/.SRCINFO
- svt-av1-psy/PKGBUILD
- svt-av1/.SRCINFO
- svt-av1/PKGBUILD
Simple fix for those Zen 4 until I investigate why exactly this happens (I can't reproduce it on Skylake X or Icelake), and then open a PR in the SVT-AV1 repository.
> Disabling native AVX512 SIMD code in svt-av1 until it gets fixed in mainline

- systemd-boot-manager/sdboot-kernel-remove.hook
- systemd-boot-manager/sdboot-manage.conf
Also fixed the remove hook because it was coded to check for a file made by a mhwd-kernel (a manjaro app)
> Allow manual entries for systemd boot to be created without being deleted.

- svt-av1-psy/.SRCINFO
- svt-av1-psy/PKGBUILD
Simple enough PR. I closed the previous one by mistake :P
It just updates it to the latest version with a few changes on how we name revisions to make it slightly easier for future maintenance.
> Update svt-av1-psy to 2.1.0 release

- nvidia/nvidia-utils/.SRCINFO
- nvidia/nvidia-utils/PKGBUILD
- nvidia/nvidia-utils/nvidia-sleep.conf
- nvidia/nvidia-utils/nvidia-utils.install
Enable these services at the initial installation.
Existing users need to enable the services manually.
Also, set NVReg Path, which fixes graphical corruption on wayland.
> nvidia-utils: Enable services for sleep and add config

- cachyos-settings/cachyos-settings.install
This prevents an error when it is already disabled or not installed.
> cachyos-settings: add is-enabled check around uksmd disable

- wine-cachyos/PKGBUILD
Hello, I noticed the URL for wine-cachyos is different than what it actually pulls from, shouldn't it be at least 
https://github.com/CachyOS/wine-cachyos ?
> Fix url for wine-cachyos PKGBUILD

- opentabletdriver/.SRCINFO
- opentabletdriver/PKGBUILD
- opentabletdriver/notes.install
- opentabletdriver/opentabletdriver.desktop
- opentabletdriver/use-libc-timerfd-in-linuxtimer.patch
Currently in opentabletdriver, a timer expiration is signaled by creating new threads. This whole process is very inefficient and can cause issues with process renicing daemons such as ananicy-cpp. The patch aims to make this more efficient and resolves the conflict with ananicy-cpp caused by the old implementation.
I am also planning to open an issue in [OpenTabletDriver's GitHub](https://github.com/OpenTabletDriver/OpenTabletDriver) to get more attention on this. Meanwhile, I believe we should patch this in as CachyOS OpenTabletDriver users are more susceptible to this bug because ananicy-cpp is enabled by default.
> Package opentabletdriver with patch to replace librt-timer with libc-timerfd

- nvidia/egl-wayland/.SRCINFO
- nvidia/egl-wayland/PKGBUILD
The patch was updated to use a common surface initializer helper function. It seems to have fixed most issues with previous versions, especially some of the niche ones that a user had.
I updated the patch file name based on https://github.com/NVIDIA/egl-wayland/commit/f30cb0e4c9a215e933dc8250f5dad4e96d4f2136 commit message.
> This fixes crashes with qt6webengine.
> egl-wayland: Update !131 Backport

- go/.SRCINFO
- go/.nvchecker.toml
- go/PKGBUILD
This adds the go package, for using GOAMD=v3/v4 optimization for the cachyos-v3, cachyos-v4 and cachyos-znver4 repository.
> go: Introduce package for GOAMD=v3/v4

- cachyos-rate-mirrors/.SRCINFO
- cachyos-rate-mirrors/PKGBUILD
- cachyos-rate-mirrors/cachyos-rate-mirrors
The CDN provides a updated archlinux mirror, which gets synced pretty frequently.
Also, most users have quite good download speed on these.
There are not too many packages pulled from this repo, therefore lets put it on the top as default after ranking.
We have been using this mirror as default for the installation and there were never real complains or issues with it at all too.
> cachyos-rate-mirrors: Use the CachyOS CDN as first mirror after ranking

- wine-cachyos/.SRCINFO
- wine-cachyos/PKGBUILD
- wine-cachyos/lto-fixup.patch
`lto-fixup.patch` is a rebase of a [patch](https://github.com/openglfreak/wine-tkg-userpatches/blob/df0a89aec388b23a8a82dca6d53e65d25c3a8f86/patches/9999-diffs/lto-fixup.patch) by Torge Matthies, which supersedes [server: Enable link-time optimization](https://github.com/CachyOS/wine-cachyos/commit/cc9ebe323b825db218fb3c257374e81fb5ebc4ed) by allowing all native modules (i.e. modules compiled without mingw) to be compiled with LTO, not just wineserver. 
The relevant compilation flags are added to the PKGBUILD.
> wine-cachyos: Enable LTO compilation for all native libraries

- zlib-ng/lib32-zlib-ng/.SRCINFO
- zlib-ng/lib32-zlib-ng/.nvchecker.toml
- zlib-ng/lib32-zlib-ng/PKGBUILD
- zlib-ng/zlib-ng/.SRCINFO
- zlib-ng/zlib-ng/.nvchecker.toml
- zlib-ng/zlib-ng/PKGBUILD
We aim to replace zlib with zlib-ng to make use of the optimizations from the next generation implementation
Some benchmarks to highlight the benefits of this replacement:
- [zlib-ng - 2.0.0 Benchmark Discussions](https://github.com/zlib-ng/zlib-ng/discussions/871)
- [AWS - Comparisons between zlib-cloudflare, zlib-ng and other zlib forks](https://aws.amazon.com/blogs/opensource/improving-zlib-cloudflare-and-comparing-performance-with-other-zlib-forks/)
- [Megastorm's Systems zlib-ng vs zlib](https://www.megastormsystems.com/news/benchmarks-results-of-zlib-and-zlib-ng-running-on-some-amd-and-intel-cpus)
Closes #330
> feat: Add zlib-ng

- power-profiles-daemon/.SRCINFO
- power-profiles-daemon/PKGBUILD
Closes #338 
Let's just maintain our own ppd instead of using Arch's. It is pretty low effort and we can cherrypick commits that introduce more fixes or even new features. We can revisit this decision if development slows down.
> power-profiles-daemon: 0.23

- zlib-ng/lib32-zlib-ng/.SRCINFO
- zlib-ng/lib32-zlib-ng/PKGBUILD
- zlib-ng/zlib-ng/.SRCINFO
- zlib-ng/zlib-ng/PKGBUILD
> zlib-ng: 2.2.2 && Add depends=(zlib-ng{,-compat}) for 32bit package

- proton-cachyos/.SRCINFO
- proton-cachyos/PKGBUILD
- wine-cachyos/.SRCINFO
- wine-cachyos/PKGBUILD
- wine-cachyos: version 9.0-20240918
- proton-cachyos: version 9.0-20240918
* Wine
- rebase-only
* Proton
- removed: (staging) d3dx11_43-D3DX11CreateTextureFromMemory
- removed: (staging) d3dx9_36-BumpLuminance
- removed: (staging) shell32-SHFileOperation_Move
- removed: (staging) shell32-registry-lookup-app
- dropped: (in-upstream) include: Add TCP_KEEPCNT and TCP_KEEPINTVL definitions.
- dropped: (in-upstream) include: ws2_32: Implement TCP_KEEP{ALIVE,CNT,INTVL} options.
-   added: gdi32,win32u,winex11: Implement D3DKMTEnumAdapters2.
-   added: win32u: Allow faking HAGS in QueryAdapterInfo.
> Update Proton/Wine to version 9.0-20240918

- cachyos-settings/.SRCINFO
- cachyos-settings/PKGBUILD
tunecfs2 and irqbalance has been dropped from cachyos-settings for quite a while now.
> cachyos-settings: Remove old optional dependencies

- chwd/.SRCINFO
- chwd/PKGBUILD
This should also fix chwd failing in ISO installs since it won't fetch the obsolete packages anymore.
> chwd: Cherrypick amd profile update due recent mesa changes

- nvidia/nvidia-550xx/nvidia-550xx-dkms/.SRCINFO
- nvidia/nvidia-550xx/nvidia-550xx-dkms/PKGBUILD
This is needed for systems to be able to replace the NVIDIA drivers correctly without invoking a forced removal (-Rdd).
> nvidia-550xx: Make it conflict with default drivers

- mesa/lib32-mesa/.SRCINFO
- mesa/lib32-mesa/PKGBUILD
- mesa/mesa/.SRCINFO
- mesa/mesa/PKGBUILD
Removed the b2sums array. Refer to commit log for rationale. It's controversial so let me know if you don't want this.
> mesa: 24.3.1

- cachyos-rate-mirrors/cachyos-rate-mirrors
Fix read permissions for Group/Other in case of more restrictive umask settings after a 'cachyos-rate-mirrors' run. Required to make third party package managers like Aura work properly.
> Fix file permissions of Pacman mirrorlist files in case of more restrictive umask

- cachy-browser/.SRCINFO
- cachy-browser/PKGBUILD
I can't test because my machine isn't powerful enough to build, but I checked gentoo's ebuild this time and didn't see any updates to the patchset so this _should_ be fine.
Old gentoo ebuild: https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/firefox/firefox-135.0.ebuild?id=c2ea9974fabd95a3fa202aeb821198ee2379f336#n6
New ebuild: https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/firefox/firefox-135.0.1.ebuild?id=c2ea9974fabd95a3fa202aeb821198ee2379f336#n6
> cachy-browser: 135.0.1-1

- handheld/cachyos-handheld/.SRCINFO
- handheld/cachyos-handheld/PKGBUILD
- handheld/lib32-gamescope-plus/.SRCINFO
- handheld/lib32-gamescope-plus/PKGBUILD
This adds the WSI layer for 32-bit gamescope-plus (what's used in handheld edition). If this isn't present, some games[1] can show very bad display corruption
[1] https://discuss.cachyos.org/t/weird-hid-render-corruption-rgb-artifacts-in-gaming-mode-handheld-edition-steam-deck-lcd/6153
> feat: Introduce lib32-gamescope-plus

- sqlite/.SRCINFO
- sqlite/PKGBUILD
- sqlite/remove-header-in-command.patch
Builds were failing due to the compiler generating both the binary and the
header. By removing the passed header to the compiler, the build
continues and succeeds gracefully.
Closes: #528
> sqlite: Fix PGO builds!

- limine-hook/.SRCINFO
- limine-hook/10-limine-add-kernel.hook
- limine-hook/10-limine-remove-kernel.hook
- limine-hook/PKGBUILD
- limine-hook/limine-kernel-hook
This adds limine-hook to automatically add boot entries after removing/installing kernels, like grub-hook. Works for UEFI users only. Note that limine-entry-tool does copy initramfs and vmlinuz to a different directory in ``/boot``, so you need to keep an eye on the free space of ESP partition.
> Add limine-hook

- cachyos-hooks/.SRCINFO
- cachyos-hooks/PKGBUILD
I don't know how I didn't notice it before, but it's a hotfix for script name in the hook.
> cachyos-hooks: 2025.04.26

- scx-scheds/scx-scheds-git/.SRCINFO
- scx-scheds/scx-scheds-git/PKGBUILD
- scx-scheds/scx-scheds/.SRCINFO
- scx-scheds/scx-scheds/PKGBUILD
Add libseccomp as a dependency for scx_rustland and protobuf as a build
dependency for scxtop
> scx-scheds: 1.0.12-2

- cachyos-hooks/.SRCINFO
- cachyos-hooks/PKGBUILD
- Adds hook to replace plymouth script for updating initrd with our own to fix issues when using limine-mkinitcpio-hook.
- Adds me as a maintainer if no one minds.
- Brings initramfs updates in generic `update-initramfs` script
- Fixes duplicate reboot notifications on system update
- Minor refactoring
Extra testing is always welcome.
> cachyos-hooks: 2025.05.14

- cachyos-rate-mirrors/.SRCINFO
- cachyos-rate-mirrors/PKGBUILD
- cachyos-rate-mirrors/cachyos-rate-mirrors
It's possible to bypass Russian censorship by using tools such as zapret, which do not change the user's IP address and thus allow access to CDN77, but cachyos-rate-mirrors still will not use it.
> cachyos-rate-mirrors: Check CDN77 availability by timeout

- mesa/mesa-git/customization.cfg
Gallium XA is deprecated and now disabled by default and will be removed in Mesa 25.2 https://gitlab.freedesktop.org/mesa/mesa/-/commit/31cf6b94ad1dfaf4272b22a39d7e2805d03f9375
> Move _gallium_xa to legacy following deprecation and frontend deletion

- lsfg-vk/.SRCINFO
- lsfg-vk/PKGBUILD
This uses the [official installation guide](https://github.com/PancakeTAS/lsfg-vk/wiki/Installation-Guide) with the only difference being the additional cmake flag `-DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,lazy"`, which removes makepkg's default `-z,now`, thereby preventing it from stripping out the necessary DXVK symbols.
> New package: lsfg-vk

- lsfg-vk/.SRCINFO
- lsfg-vk/PKGBUILD
- lsfg-vk/lsfg-vk.install
- Update `PKGBUILD` to the most recent commit
- Add new dependencies and submodules
- Fix `DCMAKE_SHARED_LINKER_FLAGS` overriding `makepkg.conf`'s default `LDFLAGS`
- Remove `LTO` from `CFLAGS` (as it breaks linkage in `liblsfg-vk.so`)
- Modify `lsfg-vk.install` to reflect upstream changes
> lsfg-vk: update PKGBUILD and .install to reflect upstream changes

- cachyos-mirrorlist/cachyos-mirrorlist
I fixed the timer issues and added the correct server path
On this mirror there is also a copy of archlinux. So as  proof of stability you also can check https://archlinux.org/mirrors/hb9hil.org/
> reenabled and fixed switzerland mirror

- lsfg-vk/.SRCINFO
- lsfg-vk/PKGBUILD
- Change the compiler to `Clang` to comply with upstream's build system
- Remove no longer needed dependencies and add new ones
- Add the new UI functionality
- Change commit to the [v0.9.0 pre-release](https://github.com/PancakeTAS/lsfg-vk/commit/7c0c29c1e74c51921b2f5455e3dc2472a6bc99c0)
> lsfg-vk: change compiler to clang && add UI app

- davinci-resolve/PKGBUILD
Updated PKGBUILD with required sha256sum and versioning. BMD has changed their versioning by the looks of it.
> Update resolve to 20.1

- cachy-update/.SRCINFO
- cachy-update/PKGBUILD
- Latest patch commit fixing tooltip's branding: https://github.com/CachyOS/cachy-update/pull/3
- `sudo-rs` support added upstream in: https://github.com/Antiz96/arch-update/pull/408
> Bump cachy-update to include latest patch commit & add missing sudo-rs optdepend

- .github/workflows/validate-pkgbuilds.yml
At the moment, the PRs are always green because the BASE and HEAD refs are the same (`origin/master`), which doesn't detect any changes. E.g., https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/871/checks
This should hopefully fix the issue by using the commit's SHA instead of what was used before.
Example test run https://github.com/azdanov/CachyOS-PKGBUILDS/actions/runs/18100784454/job/51502912207
> ci: fix PR changes not detected by validate-pkgbuilds
